# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 96e81262-dbad-477a-8019-bcbab4efc2f8-capi-aws
  namespace: 96e81262-dbad-477a-8019-bcbab4efc2f8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 96e81262-dbad-477a-8019-bcbab4efc2f8-capi-aws
subjects:
- kind: ServiceAccount
  name: 96e81262-dbad-477a-8019-bcbab4efc2f8-capi-aws
