# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: 96e81262-dbad-477a-8019-bcbab4efc2f8
rules:
  - apiGroups:
    - cluster.x-k8s.io
    resources:
    - machinedeployments
    - machinedeployments/scale
    - machines
    - machinesets
    verbs:
    - get
    - list
    - update
    - watch
